Repository Jeong-Reminder/reminder-frontend, pull requests merged in 2024-10, with the labels that each got.

#213 [Feat/#212] 기능 구현
  frontend/lib/admin/screens/userInfo_screen.dart
  frontend/lib/providers/announcement_provider.dart
  frontend/lib/screens/boardDetail_screen.dart
  frontend/lib/screens/downloadImage_screen.dart
  frontend/lib/screens/home_screen.dart
  frontend/lib/screens/myOwnerPage_screen.dart
  frontend/lib/screens/myUserPage_screen.dart
  frontend/lib/screens/totalBoard_screen.dart
  frontend/lib/screens/update_screen.dart
  frontend/lib/screens/write_screen.dart
  frontend/lib/widgets/board_widget.dart
  frontend/lib/widgets/vote_widget.dart
Labels: documentation, enhancement

#215 [Fix/#205] Android UI 및 기능 수정
  .idea/.gitignore
  .idea/misc.xml
  .idea/reminder-frontend.iml
  frontend/lib/screens/experience_screen.dart
  frontend/lib/screens/login_screen.dart
  frontend/lib/screens/makeTeam_screen.dart
  frontend/lib/screens/memberRecruit_screen.dart
  frontend/lib/screens/recruitDetail_screen.dart
  frontend/lib/screens/setExperience_screen.dart
Labels: documentation

#217 [Fix/#216] 안드로이드 실제 기기에서 MyUserPage 오버플로우 오류 수정
  frontend/lib/screens/login_screen.dart
  frontend/lib/screens/myUserPage_screen.dart
Labels: documentation

#223 [feat : #222] 개인정보처리방침 추가하기
  frontend/lib/screens/privacyPolicy_screen.dart
  frontend/lib/widgets/account_widget.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: enhancement

#230 [feat : #228] 팀원 모집 파트에서 카테고리 중복 오류 처리
  frontend/lib/screens/memberRecruit_screen.dart
  frontend/pubspec.yaml
Labels: enhancement

#233 [Feat/#232] 알림 리스트 구현
  frontend/assets/images/notification.png
  frontend/assets/images/recruit.png
  frontend/lib/main.dart
  frontend/lib/models/notification_model.dart
  frontend/lib/providers/notification_provider.dart
  frontend/lib/screens/boardDetail_screen.dart
  frontend/lib/screens/home_screen.dart
  frontend/lib/screens/notificationList_screen.dart
  frontend/lib/services/notificationList_service.dart
  frontend/lib/services/notification_services.dart
  frontend/pubspec.yaml
Labels: enhancement
